### ISSUE TITLE
caution highlight color

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-InvolveUsersAll#2]
Need less bright color. See https://github.com/w3c/wai-website-design/issues/120

currently marked up with: "&lt;mark&gt;"

not sure if that was @yatil 's suggestion or Nics?

**Comment by yatil** [comment]
The discussion is in w3c/wai-website-design#120 and the result will transcend to this resource automatically via CSS, so this issue can be closed. `<mark>` is the semantically correct element, imho.
