### ISSUE TITLE
[low priority] list continue after heading

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-InvolveUsersAll#3]
https://w3c.github.io/wai-InvolveUsersAll//plan/involving-users/#including-users-in-implementation

We want this list to start at #4 -- so it continues on from the list above.

It does in the edit view of the markdown:
> 4.  When you are considering a specific design aspect, such as expanding/collapsing navigation, find other products that are already doing it. Ask users to explore with you what works well and what does not.

but not in the rendered view

fyi, It does here: https://www.w3.org/WAI/users/involving#range
which is done with 
> ol  start ="4"

**Comment by yatil** [comment]
Fixed in 08e7729.
