### ISSUE TITLE
[!!] Inconsistency with capital letters after bullets

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-InvolveUsersAll#4]
- Introduction section - uses capital letters after each bullet.
- More Efficient Development section - uses lower case letters after each bullet.

Each of these sections are finishing the sentence just before starting the bulleted list. This is inconsistent. Choose one or the other.

**Comment by yatil** [comment]
@slhenry or (maybe) @vavroom, can you take a look? Thanks!

**Comment by shawna-slh** [comment]
fixed.

**Comment by vavroom** [comment]
Gee @slhenry I just got the email notification and you've already fixed :D

**Comment by yatil** [comment]
Ah, breath-taking speed! I’m not used to this :-D
