### ISSUE TITLE
[!!] Bug - Numbered list continues from section above

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-InvolveUsersAll#5]
In the "Including Users in Implementation" section, the numbered list starts at #4. It should start over again at #1 if it is going to be another OL.

**Comment by yatil** [comment]
@bakkenb This is actually deliberate, see #3. I find it also (mildly?) confusing.

**Comment by yatil** [comment]
@slhenry FYI ^^

**Comment by shawna-slh** [comment]
I looked at it again. The second list continues the steps from the first list, so starting at 4 is correct.

When we have time, we could think about other ways to present it.

**Comment by shawna-slh** [comment]
Actually, looking more closely, it makes sense to make the second list ul instead of ol.

Done.
